language: python
python:
  - "3.6.9"

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations custom_user
  - python manage.py makemigrations data_management
  - python manage.py test
