name: FAIR Data Registry
on: [push]
jobs:
  test:
    name: Test ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install graphviz on ubuntu
        run:  |
              if [ ${{ runner.os }} == "Linux" ]; then
                  sudo apt-get install graphviz
              else
                  brew install graphviz
              fi
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Run Tests
        run: |
          poetry install 
          source $VENV
          DJANGO_SETTINGS_MODULE=drams.test-settings coverage run --omit=drams,scripts,tools manage.py test 
      - name: Generate XML
        run: coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,PYTHON
          files: ./coverage.xml
          flags: unittests
          verbose: true
  deploy-local-registry:
    name: Deploy local registry on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.9", "3.10"]
    env:
      REGISTRY_PORT: 8001
      INSTALL_DIR: fair
    steps:
      - uses: actions/setup-python@v2
      - name: Deploy registry
        if: startsWith(github.ref, 'refs/tags/') != true
        run: curl -fsSL https://raw.githubusercontent.com/FAIRDataPipeline/data-registry/${GITHUB_REF/refs\/heads\//}/static/localregistry.sh | bash -s -- -d $INSTALL_DIR -b ${GITHUB_REF/refs\/heads\//}
      - name: Deploy registry (Tagged Release)
        if: startsWith(github.ref, 'refs/tags/')
        run: curl -fsSL https://raw.githubusercontent.com/FAIRDataPipeline/data-registry/${GITHUB_REF/refs\/tags\//}/static/localregistry.sh | bash -s -- -d $INSTALL_DIR -t ${GITHUB_REF/refs\/tags\//}
      - name: Start registry
        run:  |
              $INSTALL_DIR/registry/scripts/start_fair_registry -p $REGISTRY_PORT
      - name: Test registry
        run: curl http://localhost:$REGISTRY_PORT/api/
